# Generated by Django 4.0.4 on 2022-06-27 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, verbose_name='Titulo del contenido')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=15, verbose_name='Etiqueta')),
                ('nombre_curso', models.CharField(max_length=100, verbose_name='Nombre del Curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grado', models.CharField(max_length=1, verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo Electrónico')),
                ('nombre_institucion', models.CharField(max_length=30, verbose_name='Nombre de la Institución')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Logo')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Institución Educativa',
                'verbose_name_plural': 'Institución Educativa',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nivel', models.CharField(max_length=15, verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seccion', models.CharField(max_length=1, verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=45, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=45, verbose_name='Apellido Materno')),
                ('dni', models.CharField(max_length=8, verbose_name='dni')),
                ('celular', models.CharField(max_length=9, verbose_name='Celular')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('foto', models.ImageField(default='images/dfImage.jpg', null=True, upload_to='imagenes/', verbose_name='Foto de Perfil')),
                ('grado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.grado', verbose_name='Grado')),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.nivel', verbose_name='Nivel')),
                ('seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.seccion', verbose_name='Seccion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ID Usuario')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Detalle_alumno_en_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.curso', verbose_name='ID Curso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ID Usuario')),
            ],
            options={
                'verbose_name': 'Detalle de alumno en un curso',
                'verbose_name_plural': 'Detalle de alumno en un curso',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.grado', verbose_name='ID Grado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.nivel', verbose_name='ID Nivel'),
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.periodo', verbose_name='ID Periodo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.seccion', verbose_name='ID Seccion'),
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_folder', models.CharField(max_length=45, verbose_name='Nombre de la capeta')),
                ('es_tarea', models.BooleanField(default=False, verbose_name='¿Es tarea?')),
                ('tiempo_limite', models.DateField(null=True, verbose_name='Tiempo límite')),
                ('contenido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.contenido', verbose_name='ID Contenido')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.curso', verbose_name='ID Curso')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Inasistencia')),
                ('detalle_alumno_en_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.detalle_alumno_en_curso', verbose_name='alumno en curso')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=45, verbose_name='nombre del archivo')),
                ('ruta_archivo', models.FileField(upload_to='archivos/', verbose_name='Archivo')),
                ('visibilidad_alumno', models.BooleanField(default=False, verbose_name='visibilidad para alumno')),
                ('carpeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.carpeta', verbose_name='ID Carpeta')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
    ]
