# Generated by Django 4.0.4 on 2022-05-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=45, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=45, verbose_name='Apellido Materno')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('celular', models.CharField(max_length=9, verbose_name='Celular')),
                ('genero', models.CharField(max_length=1, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('foto', models.ImageField(upload_to='', verbose_name='Foto de Perfil')),
            ],
        ),
    ]
