# Generated by Django 4.0.4 on 2022-05-21 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0002_grado_institucion_nivel_periodo_seccion_docente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, verbose_name='Titulo del contenido')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=15, verbose_name='Etiqueta')),
                ('nombre_curso', models.CharField(max_length=100, verbose_name='Nombre del Curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterModelOptions(
            name='grado',
            options={'verbose_name': 'Grado', 'verbose_name_plural': 'Grados'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AlterField(
            model_name='institucion',
            name='logo',
            field=models.ImageField(upload_to='imagenes/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(max_length=3, verbose_name='Género'),
        ),
        migrations.CreateModel(
            name='Detalle_alumno_en_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.alumno', verbose_name='ID Alumno')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.curso', verbose_name='ID Curso')),
            ],
            options={
                'verbose_name': 'Detalle de alumno en un curso',
                'verbose_name_plural': 'Detalle de alumno en un curso',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.docente', verbose_name='ID Docente'),
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.grado', verbose_name='ID Grado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.nivel', verbose_name='ID Nivel'),
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.periodo', verbose_name='ID Periodo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.seccion', verbose_name='ID Seccion'),
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_folder', models.CharField(max_length=45, verbose_name='Nombre de la capeta')),
                ('es_tarea', models.BooleanField(default=False, verbose_name='¿Es tarea?')),
                ('tiempo_limite', models.DateField(null=True, verbose_name='Tiempo límite')),
                ('contenido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.contenido', verbose_name='ID Contenido')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.curso', verbose_name='ID Curso')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Inasistencia')),
                ('detalle_alumno_en_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.detalle_alumno_en_curso', verbose_name='alumno en curso')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=45, verbose_name='nombre del archivo')),
                ('ruta_archivo', models.FileField(null=True, upload_to='', verbose_name='Archivo')),
                ('visibilidad_alumno', models.BooleanField(default=False, verbose_name='visibilidad para alumno')),
                ('carpeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula_virtual.carpeta', verbose_name='ID Carpeta')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
    ]
