# Generated by Django 4.0.4 on 2022-06-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0003_contenido_curso_alter_alumno_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=8, verbose_name='dni'),
        ),
    ]
